-- =============================================================================
-- SOPs Seed Data for Hoffman Solutions
-- Kategorien: Onboarding, Website / OnePage, Google Ads,
--             Lead-Handling & Kundenfuehrung, Sales intern, Technik
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Onboarding
-- ---------------------------------------------------------------------------

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('After-Close-Call Ablauf', 'Onboarding', E'# After-Close-Call Ablauf\n\nSobald der Vertrag unterschrieben ist, startet der Onboarding-Prozess. Jede Minute zaehlt -- der Kunde ist jetzt am motiviertesten.\n\n## Sofort nach dem Close (innerhalb von 30 Minuten)\n\n1. **Willkommensnachricht per WhatsApp** senden mit kurzem Glueckwunsch und Ausblick auf die naechsten Schritte.\n2. **Onboarding-Formular** versenden (Link aus dem internen Template). Das Formular erfasst:\n   - Firmenname, Ansprechpartner, Telefon, E-Mail\n   - Gewerk(e) und Einzugsgebiet\n   - Vorhandene Website, Google-Zugaenge, Logo-Dateien\n   - Bisherige Marketingerfahrung\n3. **Erwartungshaltung setzen**: Klar kommunizieren, dass die erste Kampagne 7-10 Werktage nach vollstaendigen Daten live geht.\n\n## Innerhalb von 24 Stunden\n\n- Kundendaten im CRM anlegen (Firma, Kontakt, Vertragsdaten).\n- Fulfillment-Team per Slack informieren mit Zusammenfassung: Gewerk, Region, Budget, Besonderheiten.\n- Kickoff-Call mit dem Kunden terminieren (idealerweise innerhalb von 3 Tagen).\n\n## Kickoff-Call Agenda\n\n- Vorstellung Fulfillment-Ansprechpartner\n- Walkthrough der Timeline\n- Offene Fragen klaeren\n- Zugaenge einsammeln (Google Ads, ggf. Domain-Zugang)\n\n## Haeufige Fehler\n\n- Formular nicht am selben Tag senden -- der Kunde verliert Momentum.\n- Keine klare Timeline nennen -- fuehrt zu unrealistischen Erwartungen.\n- Fulfillment erst Tage spaeter informieren -- verzoegert alles.', '{admin,fulfillment}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Kundendaten-Check', 'Onboarding', E'# Kundendaten-Check\n\nBevor wir mit dem Setup starten, muessen alle Daten vollstaendig und korrekt vorliegen. Unvollstaendige Daten sind der haeufigste Grund fuer Verzoegerungen.\n\n## Pflichtdaten\n\n| Datenpunkt | Wo pruefen | Haeufiger Fehler |\n|---|---|---|\n| Firmenname (exakt) | Handelsregister / Impressum | Abkuerzungen statt voller Name |\n| Ansprechpartner + Handy | Onboarding-Formular | Festnetz statt Mobil |\n| E-Mail (fuer Leads) | Onboarding-Formular | info@-Adresse, die niemand liest |\n| Gewerk(e) | Onboarding-Formular | Zu vage, z.B. nur \"Handwerker\" |\n| Einzugsgebiet mit PLZ-Bereich | Onboarding-Formular | \"Region Stuttgart\" ohne genaue PLZ |\n| Logo in hoher Aufloesung | Cloud-Upload | JPG mit 200px Breite |\n| Google Ads Zugang | Einladung ans Team-Konto | Kunde hat kein Konto |\n| Bisherige Website-URL | Onboarding-Formular | Keine Domain vorhanden |\n| Fotos (Referenzen, Team) | Cloud-Upload | Stock-Fotos statt echte Bilder |\n\n## Pruef-Ablauf\n\n1. Formular-Eingang pruefen -- alle Felder ausgefuellt?\n2. Gegenlesen: Stimmen Firmenname und Adresse mit dem Impressum ueberein?\n3. Logo pruefen: Mindestens 1000px breit, PNG oder SVG bevorzugt.\n4. Google-Zugang testen: Einloggen und pruefen, ob Admin-Rechte vorhanden.\n5. Fehlende Daten **sofort** per WhatsApp nachfordern -- nicht per E-Mail, das dauert zu lange.\n\n## Checkliste Nachforderung\n\nWenn etwas fehlt, sende eine kurze WhatsApp:\n\n> \"Hey [Name], mir fehlen noch [X] und [Y] damit wir loslegen koennen. Kannst du mir das heute noch schicken? Dann sind wir im Zeitplan.\"\n\nMaximal 2 Nachforderungsrunden, danach Eskalation an den zustaendigen Sales-Kontakt.', '{admin,fulfillment}');

-- ---------------------------------------------------------------------------
-- 2. Website / OnePage
-- ---------------------------------------------------------------------------

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Aufbau einer Handwerker-Landingpage', 'Website / OnePage', E'# Aufbau einer Handwerker-Landingpage\n\nUnsere Landingpages haben ein klares Ziel: Der Besucher fuellt das Kontaktformular aus. Alles auf der Seite dient diesem einen Zweck.\n\n## Above the Fold (Sichtbar ohne Scrollen)\n\n- **Headline**: Gewerk + Region + Nutzenversprechen. Beispiel: \"Dachdecker in Muenchen -- Kostenlose Beratung in 24h\"\n- **Sub-Headline**: Vertrauen aufbauen, z.B. \"Ueber 200 zufriedene Kunden seit 2015\"\n- **Hero-Bild**: Echtes Foto vom Team oder einer Baustelle. Keine Stock-Fotos.\n- **CTA-Button**: Kontrastfarbe, grosse Schrift. Text: \"Jetzt kostenlos anfragen\" oder \"Kostenloses Angebot erhalten\"\n- **Formular**: Direkt sichtbar oder per Button erreichbar. Maximal 4-5 Felder (Name, Telefon, E-Mail, PLZ, kurze Beschreibung).\n\n## Trust-Elemente\n\n- Google-Bewertungen einbinden (mindestens 4.0 Sterne)\n- Logos von Zertifizierungen (Meisterbetrieb, Innungsmitglied)\n- 2-3 kurze Kundenstimmen mit Namen und Ort\n- \"Bekannt aus\" oder Partnerlogos, falls vorhanden\n\n## Seitenstruktur unterhalb des Folds\n\n1. **Leistungen**: 3-4 Kernleistungen als Kacheln mit Icon + Kurztext\n2. **So funktioniert''s**: 3 Schritte (Anfrage, Beratung, Umsetzung)\n3. **Ueber uns**: Kurzer Text + Teamfoto\n4. **FAQ**: 4-5 haeufige Fragen\n5. **Zweiter CTA-Block**: Formular oder Button erneut einblenden\n\n## Mobile-First Regeln\n\n- Formular muss mit Daumen bedienbar sein.\n- Telefonnummer ist klickbar (tel:-Link).\n- Bilder komprimiert (WebP, max 200KB).\n- Ladezeit unter 3 Sekunden (teste mit PageSpeed Insights).\n\n## Dont''s\n\n- Kein Slider -- lenkt ab und verlangsamt die Seite.\n- Keine Navigation mit 10 Links -- der Besucher soll nicht wegsurfen.\n- Kein Preis auf der Seite -- der Lead soll anrufen.', '{admin,fulfillment}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Tracking-Setup fuer OnePage', 'Website / OnePage', E'# Tracking-Setup fuer OnePage\n\nOhne sauberes Tracking koennen wir keine Kampagnen optimieren. Jede Landingpage bekommt dieses Standard-Setup.\n\n## 1. Google Tag Manager (GTM) einrichten\n\n1. Neues GTM-Konto anlegen (oder bestehendes verwenden).\n2. Container erstellen -- Benennung: \"Hoffman - [Firmenname]\".\n3. GTM-Snippet im `<head>` der Seite einbauen.\n4. Vorschau-Modus testen: Seite aufrufen, pruefen ob GTM feuert.\n\n## 2. Google Ads Conversion-Tracking\n\n1. Im Google Ads Konto unter \"Tools > Conversions\" eine neue Conversion anlegen:\n   - Name: \"Lead - [Firmenname]\"\n   - Kategorie: \"Lead / Kontaktanfrage\"\n   - Wert: Keinen festen Wert, oder durchschnittlichen Lead-Wert eintragen\n2. Conversion-ID und Label kopieren.\n3. Im GTM zwei Tags anlegen:\n   - **Google Ads Conversion Linker** -- Trigger: Alle Seiten\n   - **Google Ads Conversion Tag** -- Trigger: Formular-Submit Event\n\n## 3. Formular-Event einrichten\n\nJe nach Formular-Tool:\n\n- **Eigenes Formular**: Data-Layer Push nach erfolgreichem Submit:\n  ```javascript\n  dataLayer.push({ event: ''form_submit'' });\n  ```\n- **Typeform / externe Tools**: Redirect auf Danke-Seite, Trigger auf Page View der Danke-URL.\n\nIm GTM einen Trigger anlegen:\n- Trigger-Typ: \"Benutzerdefiniertes Ereignis\"\n- Ereignisname: `form_submit`\n\n## 4. Google Analytics 4 (optional aber empfohlen)\n\n1. GA4-Property anlegen.\n2. Mess-ID im GTM als GA4-Konfigurations-Tag hinterlegen.\n3. Formular-Event als GA4-Event taggen.\n\n## 5. Testen\n\n- GTM-Vorschau oeffnen.\n- Formular ausfuellen und absenden.\n- Pruefen: Feuert der Conversion-Tag? Erscheint die Conversion im Google Ads Konto (kann bis zu 24h dauern)?\n- Tag Assistant nutzen fuer Debugging.\n\n## Checkliste\n\n- [ ] GTM-Container live\n- [ ] Conversion Linker aktiv\n- [ ] Conversion Tag feuert bei Submit\n- [ ] Testkonversion im Ads-Konto sichtbar', '{admin,fulfillment}');

-- ---------------------------------------------------------------------------
-- 3. Google Ads
-- ---------------------------------------------------------------------------

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Kampagnenstruktur pro Gewerk', 'Google Ads', E'# Kampagnenstruktur pro Gewerk\n\nJeder Kunde bekommt eine klare, einheitliche Kontostruktur. Das macht Optimierung, Reporting und Skalierung einfach.\n\n## Grundprinzip\n\n**1 Kampagne = 1 Gewerk = 1 Region**\n\nBeispiel fuer einen Dachdecker in Stuttgart:\n- Kampagne: \"Dachdecker Stuttgart\"\n- Anzeigengruppe 1: \"Dachdecker allgemein\" (dachdecker stuttgart, dachdecker in meiner naehe)\n- Anzeigengruppe 2: \"Dachsanierung\" (dach sanieren, dachsanierung kosten)\n- Anzeigengruppe 3: \"Dach reparieren\" (dach reparatur, dach undicht)\n\n## Keyword-Logik\n\n- **Hauptkeywords**: [gewerk] + [stadt/region] als Phrase Match\n- **Longtail**: [gewerk] + [leistung] + [stadt] als Phrase Match\n- **Broad Match**: Nur bei genuegend Conversion-Daten (min. 30 Conversions) einsetzen\n- **Exact Match**: Fuer die Top-3 Keywords mit dem meisten Volumen\n\n## Negativlisten\n\nFuer jedes Konto eine geteilte Negativliste anlegen:\n\n- **Standard-Negativ** (gilt immer): jobs, ausbildung, gehalt, selber machen, diy, youtube, kostenlos, forum, wiki, bilder\n- **Gewerk-spezifisch**: Je nach Gewerk irrelevante Begriffe (z.B. bei Dachdecker: \"dachbox\", \"dachtraeger\", \"dachzelt\")\n\n## Anzeigen\n\nPro Anzeigengruppe:\n- 1 responsive Suchanzeige mit mind. 10 Headlines und 4 Descriptions\n- Headlines muessen enthalten: Gewerk, Stadt, CTA, USP\n- Anzeigenerweiterungen: Sitelinks, Callouts, Standort, Anruferweiterung\n\n## Benennung\n\nEinheitliches Schema:\n- Kampagne: `[Gewerk] - [Stadt/Region] - Search`\n- Anzeigengruppe: `[Unterthema]`\n- Das macht Reporting ueber alle Kunden hinweg vergleichbar.', '{admin,fulfillment}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Erste 14 Tage einer Kampagne', 'Google Ads', E'# Erste 14 Tage einer Kampagne\n\nDie ersten zwei Wochen sind Lernphase. Wir greifen gezielt ein, aber lassen dem Algorithmus Raum.\n\n## Tag 1-3: Launch & Monitoring\n\n- Kampagne live schalten mit Tagesbudget laut Vertrag (Standard: 20-30 EUR/Tag).\n- Gebotsstrategie: **Klicks maximieren** mit Gebotslimit.\n- Taeglich pruefen:\n  - Werden Anzeigen ausgeliefert?\n  - Stimmen die Suchbegriffe? (Suchbegriffe-Bericht taeglich!)\n  - Keine offensichtlich falschen Keywords dabei?\n\n## Tag 4-7: Erste Optimierung\n\n- Suchbegriffe-Bericht auswerten: Irrelevante Begriffe als Negativ-Keywords hinzufuegen.\n- Anzeigentexte pruefen: Welche Headlines performen? Schlechte pausieren.\n- CTR pruefen: Unter 3% deutet auf schlechte Anzeigen oder falsche Keywords hin.\n- Landingpage pruefen: Laed sie schnell? Stimmt die Botschaft mit der Anzeige ueberein?\n\n## Tag 8-14: Bewertung & Anpassung\n\n- Erste Conversions vorhanden? Wenn ja:\n  - Conversion-Daten pruefen (echte Leads oder Spam?)\n  - Ueberlegen, ob Umstellung auf \"Conversions maximieren\" sinnvoll ist (braucht min. 5 Conversions)\n- Keine Conversions?\n  - Tracking nochmal pruefen (haeufigster Fehler!)\n  - Landingpage-Formular testen\n  - Keywords zu generisch? Einzugsgebiet zu klein?\n\n## Budget-Logik\n\n- Tagesbudget = Monatsbudget / 30,4\n- Google kann bis zu 2x Tagesbudget an einem Tag ausgeben, gleicht aber ueber den Monat aus.\n- Wenn nach 7 Tagen 0 Conversions: Budget NICHT erhoehen, sondern Ursache finden.\n\n## Wann eingreifen?\n\n- **Sofort**: Falsche Suchbegriffe, Tracking kaputt, Anzeige abgelehnt\n- **Nach 3 Tagen**: CTR unter 2%, keine Impressionen\n- **Nach 7 Tagen**: Keine Conversions bei ueber 50 Klicks\n- **Nach 14 Tagen**: CPA ueber Zielwert, dann Gebaenge anpassen\n\n## Wichtig\n\nDem Kunden nach Tag 7 ein kurzes Update geben -- auch wenn die Ergebnisse noch nicht perfekt sind. Transparenz schafft Vertrauen.', '{admin,fulfillment}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Gebotsstrategie & Budget', 'Google Ads', E'# Gebotsstrategie & Budget\n\nDie richtige Gebotsstrategie zum richtigen Zeitpunkt entscheidet ueber den Kampagnenerfolg.\n\n## Strategie-Phasen\n\n### Phase 1: Start (0-15 Conversions)\n\n- **Strategie**: Klicks maximieren mit Gebotslimit\n- **Warum**: Google braucht Conversion-Daten. Ohne Daten kann der Algorithmus nicht optimieren.\n- **Gebotslimit**: Branchenabhaengig, fuer Handwerker meist 2-5 EUR pro Klick.\n\n### Phase 2: Uebergang (15-30 Conversions in 30 Tagen)\n\n- **Strategie**: Conversions maximieren (ohne Ziel-CPA)\n- **Warum**: Genug Daten fuer den Algorithmus, aber noch nicht genug fuer einen stabilen Ziel-CPA.\n- **Wichtig**: Budget muss konstant bleiben, damit der Algorithmus lernen kann.\n\n### Phase 3: Skalierung (30+ Conversions in 30 Tagen)\n\n- **Strategie**: Ziel-CPA (tCPA)\n- **Ziel-CPA berechnen**: Durchschnittlichen CPA der letzten 30 Tage nehmen, NICHT den Wunsch-CPA.\n- **Anpassung**: Ziel-CPA nur in 10-15% Schritten senken, nie mehr.\n\n## Budget-Berechnung\n\nFaustregel fuer Handwerker-Leads:\n\n- Durchschnittlicher CPC: 2-6 EUR (je nach Gewerk und Region)\n- Conversion-Rate Landingpage: 5-15%\n- Daraus ergibt sich: **20-120 EUR pro Lead**\n\nBeispielrechnung:\n- Budget: 900 EUR/Monat\n- CPC: 3 EUR = 300 Klicks\n- CR: 10% = 30 Leads\n- CPA: 30 EUR pro Lead\n\n## Wann umstellen?\n\n| Von | Auf | Bedingung |\n|---|---|---|\n| Klicks max. | Conv. max. | 15+ Conversions in 30 Tagen |\n| Conv. max. | tCPA | 30+ Conversions in 30 Tagen, stabiler CPA |\n| tCPA | zurueck zu Conv. max. | Kampagne liefert keine Impressionen mehr (tCPA zu niedrig) |\n\n## Dont''s\n\n- Nie direkt mit tCPA starten -- der Algorithmus hat keine Daten.\n- Budget nicht staendig aendern -- das stoert die Lernphase.\n- Nie Ziel-CPA auf Wunschwert setzen, der unrealistisch niedrig ist.\n- Kampagnen nicht pausieren und wieder starten -- lieber Budget reduzieren.', '{admin,fulfillment}');

-- ---------------------------------------------------------------------------
-- 4. Lead-Handling & Kundenfuehrung
-- ---------------------------------------------------------------------------

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Die 15-Minuten-Regel', 'Lead-Handling & Kundenfuehrung', E'# Die 15-Minuten-Regel\n\nDie wichtigste Regel im Lead-Handling: **Jeder Lead muss innerhalb von 15 Minuten kontaktiert werden.**\n\n## Warum 15 Minuten?\n\n- Studien zeigen: Die Chance, einen Lead zu qualifizieren, sinkt nach 5 Minuten um das **10-fache**.\n- Nach 30 Minuten ist die Wahrscheinlichkeit eines Abschlusses bereits um 21x niedriger als bei sofortiger Reaktion.\n- Der Interessent hat gerade aktiv gesucht, ein Formular ausgefuellt und ist jetzt erreichbar und offen. Dieses Zeitfenster schliesst sich schnell.\n\n## Wie erklaeren wir das dem Kunden?\n\nIm Onboarding und bei jedem Wochencheck:\n\n> \"Die Leads, die du von uns bekommst, haben gerade aktiv nach einem [Gewerk] gesucht und ihre Nummer hinterlassen. Die erwarten jetzt einen Anruf. Wenn du erst abends zurueckrufst, hat der sich laengst woanders gemeldet.\"\n\nKonkret machen:\n- \"Stell dir vor, du googelst einen Notdienst und bekommst erst am naechsten Tag einen Rueckruf.\"\n- \"Deine Mitbewerber rufen auch innerhalb von Minuten an.\"\n\n## Unser Setup dafuer\n\n1. **Lead-Benachrichtigung per E-Mail UND SMS/WhatsApp**: Nur E-Mail reicht nicht -- die wird uebersehen.\n2. **Handynummer des Ansprechpartners**: Leads muessen an die Person gehen, die tatsaechlich anruft.\n3. **Erreichbarkeit klaeren**: Wann ist der Kunde erreichbar? Wer springt ein, wenn er auf der Baustelle ist?\n\n## Wenn der Kunde sich nicht dran haelt\n\n- Beim Wochencheck ansprechen: Lead-Reaktionszeiten auswerten.\n- Konkrete Beispiele nennen: \"Lead von Dienstag 14:00 -- du hast erst Mittwoch zurueckgerufen.\"\n- Eskalation nach 2 Wochen ohne Besserung (siehe SOP \"Eskalation bei Funkstille\").', '{admin,sales,fulfillment}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Wochencheck mit dem Kunden', 'Lead-Handling & Kundenfuehrung', E'# Wochencheck mit dem Kunden\n\nJeder aktive Kunde bekommt einmal pro Woche einen kurzen Check-In. Das ist unser wichtigstes Retention-Tool.\n\n## Zeitpunkt\n\n- Fester Wochentag, idealerweise Dienstag bis Donnerstag.\n- 10-15 Minuten reichen. Laenger nur bei Problemen.\n- Per Telefon, nicht per E-Mail.\n\n## Ablauf\n\n### 1. Vorbereitung (5 Min vor dem Call)\n\n- Dashboard pruefen: Leads der letzten Woche, Kosten, CPA.\n- Lead-Status checken: Wurden alle Leads bearbeitet?\n- Notizen vom letzten Call lesen.\n\n### 2. Gespraech (10-15 Min)\n\n1. **Einstieg**: \"Hey [Name], kurzes Update fuer diese Woche.\"\n2. **Zahlen nennen**: \"Wir hatten X Leads, davon Y qualifiziert, bei Z EUR Kosten.\"\n3. **Lead-Qualitaet abfragen**: \"Wie war die Qualitaet? Konntest du alle erreichen?\"\n4. **Reaktionszeit ansprechen** (wenn noetig): \"Mir ist aufgefallen, dass 2 Leads erst nach 3 Stunden kontaktiert wurden.\"\n5. **Optimierungen erklaeren**: \"Wir haben Keywords angepasst und testen neue Anzeigentexte.\"\n6. **Abschluss**: \"Gibt''s sonst noch was? Alles klar, dann bis naechste Woche.\"\n\n### 3. Nachbereitung\n\n- Kurze Notiz im CRM: Feedback, offene Punkte.\n- Wenn Action Items: Sofort erledigen oder Ticket erstellen.\n\n## Rote Flaggen\n\n- Kunde geht 2x hintereinander nicht ans Telefon --> WhatsApp senden.\n- Kunde sagt \"Leads sind schlecht\" ohne Details --> Konkrete Beispiele erfragen.\n- Kunde bearbeitet Leads nicht --> 15-Minuten-Regel nochmal erklaeren, Eskalation vorbereiten.\n- Kunde will Budget senken --> Erstmal Zahlen pruefen, CPA argumentieren.\n\n## Template WhatsApp (wenn Anruf verpasst)\n\n> \"Hey [Name], wollte gerade unser Wochen-Update machen. Kurz zusammengefasst: [X] Leads diese Woche bei [Y] EUR. Wann passt es dir fuer 5 Min?\"', '{admin,sales,fulfillment}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Eskalation bei Funkstille', 'Lead-Handling & Kundenfuehrung', E'# Eskalation bei Funkstille\n\nWenn ein Kunde Leads nicht bearbeitet oder nicht mehr erreichbar ist, handeln wir nach einem klaren Stufenplan. Ziel: Den Kunden aktivieren, bevor das Verhaeltnis kippt.\n\n## Warum ist Funkstille gefaehrlich?\n\n- Unbearbeitete Leads = verbranntes Budget = unzufriedener Kunde.\n- Kunden, die nicht reagieren, kuendigen spaeter oft mit der Begruendung \"hat nichts gebracht\".\n- Frueher eingreifen = hoehere Chance, den Kunden zu halten.\n\n## Eskalationsstufen\n\n### Stufe 1: Freundliche Erinnerung (nach 2-3 unbeantworteten Leads)\n\n- WhatsApp an den Kunden:\n\n> \"Hey [Name], mir ist aufgefallen, dass die letzten Leads noch offen sind. Konntest du die erreichen? Kurze Rueckmeldung waere super, damit wir die Kampagne optimal steuern koennen.\"\n\n- Ton: Locker, unterstuetzend, kein Vorwurf.\n\n### Stufe 2: Direkter Anruf (nach 1 Woche ohne Reaktion)\n\n- Anrufen und klar ansprechen:\n  - \"Mir faellt auf, dass seit [Datum] kein Lead bearbeitet wurde.\"\n  - \"Gibt es ein Problem? Bist du im Urlaub? Soll jemand anders die Leads bekommen?\"\n- Loesungen anbieten:\n  - Leads an anderen Mitarbeiter weiterleiten\n  - Benachrichtigung umstellen (SMS statt E-Mail)\n  - Kurze Pause der Kampagne\n\n### Stufe 3: Formelle Nachricht (nach 2 Wochen ohne Reaktion)\n\n- WhatsApp + E-Mail:\n\n> \"Hey [Name], wir konnten dich seit 2 Wochen nicht erreichen. Wir pausieren die Kampagne, damit kein Budget verbrennt. Meld dich bitte, damit wir das klaeren.\"\n\n- Kampagne tatsaechlich pausieren.\n\n### Stufe 4: Internes Review (nach 3 Wochen)\n\n- Gespraech mit Sales-Verantwortlichem: Kuendigt der Kunde? Gibt es ein Beziehungsproblem?\n- Entscheidung: Weiter pausieren, neuer Anlauf, oder Vertrag sauber beenden.\n\n## Dokumentation\n\nJeder Eskalationsschritt wird im CRM mit Datum und Massnahme dokumentiert. Das schuetzt uns bei Streitfaellen.', '{admin,sales,fulfillment}');

-- ---------------------------------------------------------------------------
-- 5. Sales intern
-- ---------------------------------------------------------------------------

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Opener-Skript: Erstgespraech', 'Sales intern', E'# Opener-Skript: Erstgespraech\n\nDas Erstgespraech ist ein Cold Call. Ziel ist NICHT der Verkauf, sondern einen Termin fuer ein ausfuehrliches Gespraech (Setter-/Closer-Call) zu vereinbaren.\n\n## Einstieg (Die ersten 10 Sekunden)\n\n> \"Hey [Name], hier ist [dein Name] von Hoffman Solutions. Kurze Frage -- du bist doch [Gewerk] in [Stadt], richtig?\"\n\n- Warte auf Bestaetigung.\n- Kein langer Monolog. Kein \"Ich ruf an weil wir...\"\n\n## Ueberleitung\n\n> \"Super. Wir helfen Handwerksbetrieben wie deinem, ueber Google gezielt Anfragen von Kunden aus der Region zu bekommen. Habt ihr da aktuell schon was laufen, oder macht ihr das noch ueber Empfehlungen?\"\n\n- Zuhoeren. Nicht sofort pitchen.\n- Wenn der Kunde erwaehnt, dass er schon Werbung macht: \"Ah cool, und bist du zufrieden damit?\"\n\n## Qualifizierungsfragen\n\n1. \"Wie viele Mitarbeiter habt ihr aktuell?\" (Mindestens 3-5, sonst zu klein)\n2. \"Was ist euer Hauptgewerk?\" (Muss klar definierbar sein)\n3. \"In welchem Umkreis arbeitet ihr?\" (Brauchen wir fuer die Kampagne)\n4. \"Habt ihr schon mal Online-Werbung gemacht?\" (Einordnung Erfahrungslevel)\n\n## Einwandbehandlung\n\n| Einwand | Antwort |\n|---|---|\n| \"Kein Interesse\" | \"Verstehe ich. Kurze Frage: Haettest du aktuell Kapazitaet, wenn morgen 5 Anfragen reinkommen wuerden?\" |\n| \"Zu teuer\" | \"Ich hab noch gar keinen Preis genannt. Lass uns kurz quatschen, ob es ueberhaupt passt.\" |\n| \"Schlechte Erfahrung gemacht\" | \"Darf ich fragen, was genau nicht funktioniert hat? Wir machen einiges anders.\" |\n| \"Keine Zeit\" | \"Verstehe, wann passt es dir besser? Brauchen nur 15 Minuten.\" |\n\n## Termin setzen\n\n> \"Ich wuerde vorschlagen, wir machen einen kurzen Termin, 15 Minuten. Da kann mein Kollege dir genau zeigen, wie das fuer [Gewerk] in [Stadt] aussehen wuerde. Passt dir eher morgen oder uebermorgen?\"\n\n- Immer Alternativfrage (\"morgen oder uebermorgen\"), nicht \"wann passt dir\".\n- Termin sofort in Calendly / CRM eintragen.', '{admin,sales}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Closing-Ablauf', 'Sales intern', E'# Closing-Ablauf\n\nDer Closing-Call ist das ausfuehrliche Verkaufsgespraech. Hier praesentieren wir die Loesung und schliessen den Vertrag ab.\n\n## Vorbereitung (15 Min vorher)\n\n- CRM-Notizen vom Opener lesen: Gewerk, Region, Teamgroesse, Schmerzpunkte.\n- Referenz-Case vorbereiten: Einen Kunden aus derselben Branche.\n- Preispaket festlegen basierend auf Region und Gewerk.\n- Bildschirm teilen vorbereiten (Beispiel-Landingpage, Referenz-Ergebnisse).\n\n## Call-Agenda (30-45 Min)\n\n### 1. Rapport (5 Min)\n\n- Lockerer Einstieg, Bezug auf den Opener-Call nehmen.\n- \"Mein Kollege hat mir erzaehlt, dass ihr [Gewerk] in [Stadt] macht und gerade [Situation]. Stimmt das so?\"\n\n### 2. Ist-Analyse (10 Min)\n\n- Wo kommen aktuell Kunden her?\n- Was kostet ein Neukunde aktuell (auch wenn per Empfehlung -- was ist der Wert)?\n- Was ist das groesste Problem: Zu wenig Anfragen? Falsche Anfragen? Schwankungen?\n- Klare Schmerzpunkte herausarbeiten und spiegeln.\n\n### 3. Loesung praesentieren (10 Min)\n\n- Bildschirm teilen: Beispiel-Landingpage zeigen.\n- Google Ads Logik erklaeren (einfach: \"Wenn jemand ''Dachdecker Muenchen'' googelt, erscheint ihr ganz oben\").\n- Referenz-Case zeigen: \"Fuer [aehnlicher Betrieb] generieren wir X Leads pro Monat bei Y EUR.\"\n\n### 4. Preis & Abschluss (10 Min)\n\n- Preis als Investment framen, nicht als Kosten.\n- \"Die Zusammenarbeit liegt bei [Betrag] pro Monat, plus Werbebudget direkt an Google. Mindestlaufzeit [X] Monate.\"\n- Stille aushalten nach dem Preis. Nicht nachschieben.\n- Einwaende behandeln:\n  - \"Zu teuer\" --> \"Was waere dir ein Neukunde wert, der 5.000 EUR Auftrag bringt?\"\n  - \"Muss drueber nachdenken\" --> \"Verstehe ich. Was genau musst du dir ueberlegen?\"\n  - \"Muss mit Partner sprechen\" --> \"Koennen wir den kurz dazuholen?\"\n\n### 5. After-Close (5 Min)\n\n- Vertrag per E-Mail senden (digitale Unterschrift).\n- Naechste Schritte erklaeren (Onboarding-Formular kommt in 30 Min).\n- Begeisterung teilen: \"Freut mich, dass wir zusammenarbeiten. Ihr werdet sehen, das lohnt sich.\"\n- Uebergabe an Fulfillment einleiten (siehe SOP \"After-Close-Call Ablauf\").', '{admin,sales}');

-- ---------------------------------------------------------------------------
-- 6. Technik
-- ---------------------------------------------------------------------------

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Vercel Deploy & Domains', 'Technik', E'# Vercel Deploy & Domains\n\nWir deployen alle Landingpages und internen Tools ueber Vercel. Hier ist der Standard-Ablauf.\n\n## Neues Projekt deployen\n\n1. **Repository vorbereiten**: Code liegt in GitHub (Organisation: Hoffman Solutions).\n2. **Vercel verbinden**:\n   - Auf vercel.com einloggen (Team-Account).\n   - \"Add New Project\" klicken.\n   - GitHub-Repo auswaehlen.\n   - Framework-Preset pruefen (Next.js, oder \"Other\" fuer statische Seiten).\n   - Environment Variables setzen, falls noetig.\n   - \"Deploy\" klicken.\n3. **Build pruefen**: Unter \"Deployments\" den Build-Log checken. Gruener Haken = alles OK.\n\n## Domain anbinden\n\n1. Im Vercel-Projekt unter \"Settings > Domains\".\n2. Domain eingeben (z.B. `kunde-gewerk.de`).\n3. Vercel zeigt die benoetigten DNS-Einstellungen:\n   - **Option A (empfohlen)**: Nameserver auf Vercel umstellen.\n   - **Option B**: A-Record auf `76.76.21.21` und CNAME `cname.vercel-dns.com`.\n4. Beim Domain-Provider (meist IONOS, Strato, oder united-domains) die DNS-Eintraege aendern.\n5. Warten bis DNS propagiert (kann bis zu 48h dauern, meist aber <1h).\n6. SSL-Zertifikat wird automatisch von Vercel erstellt.\n\n## Preview vs Production\n\n- **Production**: Jeder Push auf den `main`-Branch deployed automatisch auf die Live-Domain.\n- **Preview**: Jeder Push auf einen anderen Branch erstellt eine Preview-URL (z.B. `projekt-xyz-abc123.vercel.app`).\n- **Workflow**: Immer erst auf einem Feature-Branch arbeiten, Preview testen, dann in `main` mergen.\n\n## Haeufige Fehler\n\n- **Build schlaegt fehl**: Meistens fehlende Environment Variables oder TypeScript-Fehler. Build-Log lesen!\n- **Domain zeigt nicht auf Vercel**: DNS-Eintraege falsch gesetzt. Mit `dig domain.de` pruefen.\n- **\"Invalid Configuration\"**: Oft ein falsches Framework-Preset. Unter Settings > General aendern.\n- **Alte Version sichtbar**: Browser-Cache leeren oder Vercel Deployment manuell triggern (\"Redeploy\").', '{admin,fulfillment}');

insert into public.sops (titel, kategorie, inhalt, rolle_sichtbar) values
('Supabase Basics', 'Technik', E'# Supabase Basics\n\nSupabase ist unsere Datenbank und Backend fuer interne Tools (Dashboard, CRM-Sync, etc.). Hier das Wichtigste.\n\n## Dashboard-Zugang\n\n1. Gehe auf [supabase.com](https://supabase.com) und logge dich mit dem Team-Account ein.\n2. Waehle das richtige Projekt aus (Benennung: `hoffman-[tool-name]`).\n3. Im Dashboard findest du:\n   - **Table Editor**: Daten ansehen und bearbeiten (wie eine Tabelle).\n   - **SQL Editor**: SQL-Abfragen direkt ausfuehren.\n   - **Authentication**: User-Verwaltung.\n   - **Storage**: Dateien (Logos, Bilder).\n\n## SQL Editor verwenden\n\nFuer schnelle Abfragen:\n\n```sql\n-- Alle Kunden anzeigen\nSELECT * FROM kunden WHERE aktiv = true;\n\n-- Leads der letzten 7 Tage\nSELECT * FROM leads\nWHERE created_at > now() - interval ''7 days''\nORDER BY created_at DESC;\n```\n\n- Immer erst mit `SELECT` pruefen, bevor du `UPDATE` oder `DELETE` ausfuehrst.\n- Bei `UPDATE`/`DELETE` immer eine `WHERE`-Klausel verwenden. Nie ohne!\n\n## Row Level Security (RLS)\n\nRLS bestimmt, wer welche Daten sehen und bearbeiten darf.\n\n- **RLS ist standardmaessig aktiviert**: Ohne Policy sieht niemand etwas (auch nicht die App!).\n- Neue Tabelle erstellt? Dann brauchst du mindestens eine Policy:\n  ```sql\n  -- Beispiel: Authentifizierte User duerfen lesen\n  CREATE POLICY \"Users can read\" ON tabelle\n  FOR SELECT TO authenticated USING (true);\n  ```\n- Im Dashboard unter \"Authentication > Policies\" kannst du Policies auch per UI erstellen.\n\n## Haeufige Fehler\n\n| Problem | Ursache | Loesung |\n|---|---|---|\n| App zeigt keine Daten | RLS Policy fehlt | Policy fuer SELECT anlegen |\n| \"permission denied\" | Falsche Rolle | Pruefen ob `anon` oder `authenticated` Key verwendet wird |\n| Daten verschwunden | Falsches Projekt ausgewaehlt | Projekt-URL in der .env pruefen |\n| Langsame Abfragen | Fehlender Index | Index auf haeufig gefilterte Spalten anlegen |\n| Login geht nicht | E-Mail-Bestaetigung aktiv | Unter Auth > Settings E-Mail-Confirm deaktivieren (nur Dev!) |\n\n## Umgebungsvariablen\n\nJedes Projekt braucht diese Variablen in der `.env`:\n\n```\nNEXT_PUBLIC_SUPABASE_URL=https://xxx.supabase.co\nNEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ...\nSUPABASE_SERVICE_ROLE_KEY=eyJ... (nur serverseitig, nie im Frontend!)\n```\n\n**Wichtig**: Den Service Role Key niemals im Frontend oder in oeffentlichen Repos verwenden.', '{admin,fulfillment}');
